{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "05e14bb9-78f2-49b0-83e7-e2b72453a1e0",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pandas==2.1.4 in /Users/vals/anaconda3/lib/python3.11/site-packages (2.1.4)\n",
      "Requirement already satisfied: numpy==1.26.4 in /Users/vals/anaconda3/lib/python3.11/site-packages (1.26.4)\n",
      "Requirement already satisfied: scikit-learn in /Users/vals/anaconda3/lib/python3.11/site-packages (1.3.0)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /Users/vals/anaconda3/lib/python3.11/site-packages (from pandas==2.1.4) (2.8.2)\n",
      "Requirement already satisfied: pytz>=2020.1 in /Users/vals/anaconda3/lib/python3.11/site-packages (from pandas==2.1.4) (2023.3.post1)\n",
      "Requirement already satisfied: tzdata>=2022.1 in /Users/vals/anaconda3/lib/python3.11/site-packages (from pandas==2.1.4) (2023.3)\n",
      "Requirement already satisfied: scipy>=1.5.0 in /Users/vals/anaconda3/lib/python3.11/site-packages (from scikit-learn) (1.11.1)\n",
      "Requirement already satisfied: joblib>=1.1.1 in /Users/vals/anaconda3/lib/python3.11/site-packages (from scikit-learn) (1.2.0)\n",
      "Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/vals/anaconda3/lib/python3.11/site-packages (from scikit-learn) (2.2.0)\n",
      "Requirement already satisfied: six>=1.5 in /Users/vals/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas==2.1.4) (1.16.0)\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "!{sys.executable} -m pip install pandas==2.1.4 numpy==1.26.4 scikit-learn\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "9a506b34-ab71-4944-b5fb-405d7057dbb5",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "import os\n",
    "import re\n",
    "import glob\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from io import StringIO\n",
    "from sklearn.metrics import mean_absolute_error, r2_score\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "import xgboost as xgb\n",
    "import matplotlib\n",
    "matplotlib.use(\"Agg\")\n",
    "import warnings\n",
    "warnings.filterwarnings(\"ignore\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "c5cc42e2-ed59-4288-9025-853d7b7f964a",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Approval rate distribution:\n",
      "  Mean:   81.6%\n",
      "  Median: 87.4%\n",
      "  ✅ Strong   (>= 60th pct): 90.3%\n",
      "  🟡 Moderate (>= 30th pct): 79.8%\n",
      "  ❌ Low      (<  30th pct)\n",
      "\n",
      "MAE : 0.0429\n",
      "R²  : 0.8057\n",
      "Predicted spread (std): 13.4%\n",
      "                                                       form avg_actual predicted    outlook\n",
      "                                                      N-300     100.0%     96.4%   ✅ Strong\n",
      "                                                      I-800      96.7%     95.3%   ✅ Strong\n",
      "                                                      I-751      94.8%     95.1%   ✅ Strong\n",
      "                                                     I-821D      97.1%     95.0%   ✅ Strong\n",
      "                                                      I-821      95.3%     95.0%   ✅ Strong\n",
      "                                                       I-90      94.8%     94.9%   ✅ Strong\n",
      "                                                      I-829      93.7%     93.1%   ✅ Strong\n",
      "                                                      I-765      91.7%     92.5%   ✅ Strong\n",
      "                                                      N-600      92.5%     92.4%   ✅ Strong\n",
      "                       Immigrant Petition for Alien Workers      92.4%     92.1%   ✅ Strong\n",
      "                                                      I-140      91.4%     91.3%   ✅ Strong\n",
      "                                                      I-485      90.7%     90.3%   ✅ Strong\n",
      "                 Application for Certificate of Citizenship      91.4%     89.9% 🟡 Moderate\n",
      "                                                      I-130      90.0%     89.5% 🟡 Moderate\n",
      "                                                      N-400      88.7%     89.3% 🟡 Moderate\n",
      "                                                     I-601A      90.1%     89.1% 🟡 Moderate\n",
      "                                                      I-956      78.9%     88.8% 🟡 Moderate\n",
      "                                                     I-526E      94.1%     88.4% 🟡 Moderate\n",
      "                                                      N-565      88.2%     88.4% 🟡 Moderate\n",
      "                                                      I-589      83.6%     86.7% 🟡 Moderate\n",
      "                                                      I-881      88.1%     86.6% 🟡 Moderate\n",
      "                                                      I-824      85.8%     85.3% 🟡 Moderate\n",
      "                                                      I-730      85.4%     84.9% 🟡 Moderate\n",
      "                                                      I-600      83.9%     84.4% 🟡 Moderate\n",
      "                                                      I-929      83.8%     83.3% 🟡 Moderate\n",
      "                                                      I-539      84.8%     83.3% 🟡 Moderate\n",
      "                                                      I-817      82.2%     83.2% 🟡 Moderate\n",
      "Petition for Qualifying Family Member of a U-1 Nonimmigrant      83.4%     83.0% 🟡 Moderate\n",
      "                                                      I-131      81.6%     81.8% 🟡 Moderate\n",
      "                                                      I-914      77.2%     81.7% 🟡 Moderate\n",
      "                                                      I-129      82.5%     81.6% 🟡 Moderate\n",
      "                                                      I-360      83.7%     81.5% 🟡 Moderate\n",
      "                                                  Waivers23      79.7%     81.2% 🟡 Moderate\n",
      "                                                     I-956F      74.7%     80.8% 🟡 Moderate\n",
      "                                                      I-526      78.7%     80.6% 🟡 Moderate\n",
      "                                                     I-129F      77.5%     80.0% 🟡 Moderate\n",
      "                                                      I-924      64.9%     76.3%      ❌ Low\n",
      "                                                      I-102      73.3%     75.5%      ❌ Low\n",
      "                                                      I-193      71.8%     74.9%      ❌ Low\n",
      "                                                    Waivers      75.3%     74.7%      ❌ Low\n",
      "                                                      I-918      69.3%     74.5%      ❌ Low\n",
      "                                                      N-648      77.8%     73.1%      ❌ Low\n",
      "                         Petition for U Nonimmigrant Status      70.4%     68.5%      ❌ Low\n",
      "                      Application for T Nonimmigrant Status      61.6%     64.4%      ❌ Low\n",
      "                                          Legalization/ SAW       0.0%      6.8%      ❌ Low\n",
      "                                                      N-470      57.6%     56.2%      ❌ Low\n",
      "                                                      I-870      56.5%     55.7%      ❌ Low\n",
      "                                                      N-336      56.3%     55.7%      ❌ Low\n",
      "                                                     I-290B      47.7%     48.6%      ❌ Low\n",
      "                                                      I-899      34.2%     46.2%      ❌ Low\n",
      "                                              Legalization6      26.9%     32.7%      ❌ Low\n",
      "                                               Legalization      19.0%     14.5%      ❌ Low\n"
     ]
    }
   ],
   "source": [
    "FOLDER = '/Users/vals/Desktop/HACKATHON/'\n",
    "\n",
    "DESCRIPTION_TO_FORM = {\n",
    "    'Immediate and Preference Relatives': 'I-130',\n",
    "    'Immediate and Preference Relative':  'I-130',\n",
    "    'Family-Based Adjustments':           'I-485',\n",
    "    'Employment-Based Adjustments':       'I-485',\n",
    "    'Asylum Adjustments':                 'I-485',\n",
    "    'Refugee Adjustments':                'I-485',\n",
    "    'Cuban Adjustment Act':               'I-485',\n",
    "    'Other Adjustments of Status':        'I-485',\n",
    "    'Indo Chinese Adjustments':           'I-485',\n",
    "    'Military Naturalization':            'N-400',\n",
    "    'Orphan Petitions':                   'I-600',\n",
    "    'Convention Country Adoptions':       'I-800',\n",
    "    'Nonimmigrant Worker Petitions':      'I-129',\n",
    "    'Immigrant Petitions for Workers':    'I-140',\n",
    "}\n",
    "\n",
    "def clean_number(value):\n",
    "    if pd.isna(value):\n",
    "        return None\n",
    "    value = str(value).strip()\n",
    "    if value.upper() == 'D':\n",
    "        return None\n",
    "    if value in ('-', '–', '—', 'N/A', 'n/a', ''):\n",
    "        return 0\n",
    "    value = value.replace(',', '')\n",
    "    try:\n",
    "        return int(float(value))\n",
    "    except:\n",
    "        return None\n",
    "\n",
    "def is_numeric_cell(value) -> bool:\n",
    "    if pd.isna(value):\n",
    "        return True\n",
    "    s = str(value).strip().replace(',', '')\n",
    "    if s in ('D', '-', '–', '—', 'N/A', ''):\n",
    "        return True\n",
    "    try:\n",
    "        float(s)\n",
    "        return True\n",
    "    except:\n",
    "        return False\n",
    "\n",
    "def clean_form_number(form):\n",
    "    form = str(form).strip()\n",
    "    form = re.sub(r'\\s+\\d+$', '', form)\n",
    "    return form\n",
    "\n",
    "def get_year(filename):\n",
    "    match = re.search(r'fy(\\d{4}|\\d{2})', filename, re.IGNORECASE)\n",
    "    if not match:\n",
    "        return None\n",
    "    year = match.group(1)\n",
    "    return int('20' + year) if len(year) == 2 else int(year)\n",
    "\n",
    "def read_csv_safe(filepath):\n",
    "    for encoding in ['utf-8-sig', 'latin1', 'cp1252']:\n",
    "        try:\n",
    "            with open(filepath, 'rb') as f:\n",
    "                raw = f.read()\n",
    "            content = raw.decode(encoding, errors='replace')\n",
    "            content = content.replace('\\r\\n', '\\n').replace('\\r', '\\n')\n",
    "            lines   = content.split('\\n')\n",
    "            if ',' not in lines[0]:\n",
    "                content = '\\n'.join(lines[1:])\n",
    "            df = pd.read_csv(StringIO(content), header=None, on_bad_lines='skip')\n",
    "            if df.shape[0] > 1 and df.shape[1] > 1:\n",
    "                return df\n",
    "        except:\n",
    "            continue\n",
    "    return pd.DataFrame()\n",
    "\n",
    "def parse_old_file(filepath):\n",
    "    df       = read_csv_safe(filepath)\n",
    "    filename = os.path.basename(filepath)\n",
    "    year     = get_year(filename)\n",
    "\n",
    "    quarters_with_desc = {1:(3,4,5,6), 2:(7,8,9,10), 3:(11,12,13,14), 4:(15,16,17,18)}\n",
    "    quarters_no_desc   = {1:(2,3,4,5), 2:(6,7,8,9),  3:(10,11,12,13), 4:(14,15,16,17)}\n",
    "\n",
    "    start_row = 5\n",
    "    for i, row in df.iterrows():\n",
    "        if 'TOTAL' in str(row[0]).upper():\n",
    "            start_row = i + 1\n",
    "            break\n",
    "\n",
    "    rows = []\n",
    "    current_category = None\n",
    "\n",
    "    for i in range(start_row, len(df)):\n",
    "        row  = df.iloc[i]\n",
    "        col0 = str(row[0]).strip() if not pd.isna(row[0]) else ''\n",
    "        col1 = str(row[1]).strip() if not pd.isna(row[1]) else ''\n",
    "        col2 = str(row[2]).strip() if not pd.isna(row[2]) else ''\n",
    "\n",
    "        if not col0 and not col1:\n",
    "            continue\n",
    "        if col0 and not col1:\n",
    "            current_category = col0\n",
    "            continue\n",
    "        if not col1 or col1 == 'nan':\n",
    "            continue\n",
    "\n",
    "        form = col1\n",
    "        if is_numeric_cell(col2):\n",
    "            desc     = None\n",
    "            quarters = quarters_no_desc\n",
    "        else:\n",
    "            desc     = col2 if col2 not in ('nan', '') else None\n",
    "            quarters = quarters_with_desc\n",
    "\n",
    "        if form in DESCRIPTION_TO_FORM:\n",
    "            form = DESCRIPTION_TO_FORM[form]\n",
    "        if desc and desc in DESCRIPTION_TO_FORM:\n",
    "            form = DESCRIPTION_TO_FORM[desc]\n",
    "        form = clean_form_number(form)\n",
    "\n",
    "        for quarter_num, (r, a, d, p) in quarters.items():\n",
    "            received = clean_number(row[r]) if r < len(row) else None\n",
    "            approved = clean_number(row[a]) if a < len(row) else None\n",
    "            denied   = clean_number(row[d]) if d < len(row) else None\n",
    "            pending  = clean_number(row[p]) if p < len(row) else None\n",
    "            has_data = any(v is not None for v in [received, approved, denied, pending])\n",
    "            if has_data:\n",
    "                rows.append({\n",
    "                    'fiscal_year': year, 'quarter': quarter_num,\n",
    "                    'category': current_category, 'form_number': form,\n",
    "                    'description': desc, 'received': received,\n",
    "                    'approved': approved, 'denied': denied,\n",
    "                    'pending': pending, 'source_file': filename,\n",
    "                })\n",
    "    return pd.DataFrame(rows)\n",
    "\n",
    "\n",
    "def parse_new_file(filepath):\n",
    "    df       = read_csv_safe(filepath)\n",
    "    filename = os.path.basename(filepath)\n",
    "    year     = get_year(filename)\n",
    "\n",
    "    q_match = re.search(r'q(\\d)', filename, re.IGNORECASE)\n",
    "    quarter = int(q_match.group(1)) if q_match else None\n",
    "\n",
    "    header_row = None\n",
    "    for i, row in df.iterrows():\n",
    "        if any('Forms Received' in str(v) for v in row.values):\n",
    "            header_row = i\n",
    "            break\n",
    "    if header_row is None:\n",
    "        return pd.DataFrame()\n",
    "\n",
    "    headers = [str(v) for v in df.iloc[header_row].tolist()]\n",
    "    def find_all_columns(keyword):\n",
    "        return [i for i, h in enumerate(headers) if keyword.lower() in h.lower()]\n",
    "\n",
    "    col_received_list = find_all_columns('forms received')\n",
    "    col_approved_list = find_all_columns('approved')\n",
    "    col_denied_list   = find_all_columns('denied')\n",
    "    col_pending_list  = find_all_columns('pending')\n",
    "\n",
    "    rows = []\n",
    "    current_category = None\n",
    "\n",
    "    for i in range(header_row + 1, len(df)):\n",
    "        row  = df.iloc[i]\n",
    "        form = str(row[0]).strip() if not pd.isna(row[0]) else ''\n",
    "        desc = str(row[1]).strip() if not pd.isna(row[1]) else ''\n",
    "        if not form or form in ['nan', 'TOTAL', 'Total']:\n",
    "            continue\n",
    "        if not desc or desc == 'nan':\n",
    "            current_category = form\n",
    "            continue\n",
    "        if form in DESCRIPTION_TO_FORM:\n",
    "            form = DESCRIPTION_TO_FORM[form]\n",
    "        if desc in DESCRIPTION_TO_FORM:\n",
    "            form = DESCRIPTION_TO_FORM[desc]\n",
    "        form = clean_form_number(form)\n",
    "\n",
    "        received = sum(clean_number(row[c]) or 0 for c in col_received_list) or None\n",
    "        approved = sum(clean_number(row[c]) or 0 for c in col_approved_list) or None\n",
    "        denied   = sum(clean_number(row[c]) or 0 for c in col_denied_list)   or None\n",
    "        pending  = sum(clean_number(row[c]) or 0 for c in col_pending_list)  or None\n",
    "        has_data = any(v is not None for v in [received, approved, denied, pending])\n",
    "        if has_data:\n",
    "            rows.append({\n",
    "                'fiscal_year': year, 'quarter': quarter,\n",
    "                'category': current_category, 'form_number': form,\n",
    "                'description': desc, 'received': received,\n",
    "                'approved': approved, 'denied': denied,\n",
    "                'pending': pending, 'source_file': filename,\n",
    "            })\n",
    "    return pd.DataFrame(rows)\n",
    "\n",
    "\n",
    "all_files = [\n",
    "    f for f in glob.glob(os.path.join(FOLDER, '*.csv'))\n",
    "    if 'unified' not in os.path.basename(f).lower()\n",
    "]\n",
    "all_data = []\n",
    "for filepath in sorted(all_files):\n",
    "    filename = os.path.basename(filepath)\n",
    "    year     = get_year(filename)\n",
    "    try:\n",
    "        result = parse_new_file(filepath) if (year and year >= 2021) else parse_old_file(filepath)\n",
    "        if not result.empty:\n",
    "            all_data.append(result)\n",
    "    except Exception as error:\n",
    "        print(f\"  {filename} → ERROR: {error}\")\n",
    "\n",
    "final = pd.concat(all_data, ignore_index=True)\n",
    "final = final.sort_values(['fiscal_year', 'quarter', 'form_number']).reset_index(drop=True)\n",
    "\n",
    "for col in ['received', 'approved', 'denied', 'pending']:\n",
    "    final[col] = pd.to_numeric(final[col], errors='coerce')\n",
    "\n",
    "final = final.sort_values(['form_number', 'fiscal_year', 'quarter']).reset_index(drop=True)\n",
    "final['pending_last_year_same_q'] = final.groupby('form_number')['pending'].shift(4)\n",
    "final['pending_imp'] = final['pending'].copy()\n",
    "final['pending_imp'] = final['pending_imp'].fillna(final['pending_last_year_same_q'])\n",
    "final['pending_imp'] = final.groupby('form_number')['pending_imp'].ffill()\n",
    "final['pending_imp'] = final.groupby('form_number')['pending_imp'].bfill()\n",
    "final = final.drop(columns=['pending_last_year_same_q'])\n",
    "final['form_id'] = final['form_number'].str.extract(r'([A-Z]{1,4}-\\d{2,3}[A-Z]?)')\n",
    "final.to_csv(os.path.join(FOLDER, 'uscis_unified_2015_2025.csv'), index=False)\n",
    "\n",
    "\n",
    "df = final.copy()\n",
    "df['form_id'] = df['form_id'].fillna(df['form_number'])\n",
    "\n",
    "df = df.groupby(['fiscal_year', 'quarter', 'form_id'], as_index=False).agg(\n",
    "    received   =('received',    'sum'),\n",
    "    approved   =('approved',    'sum'),\n",
    "    denied     =('denied',      'sum'),\n",
    "    pending_imp=('pending_imp', 'sum'),\n",
    ")\n",
    "\n",
    "df = df.dropna(subset=['approved', 'denied', 'form_id'])\n",
    "df = df[df['approved'] + df['denied'] > 0].copy()\n",
    "df['total']         = df['approved'] + df['denied']\n",
    "df['approval_rate'] = df['approved'] / df['total']\n",
    "\n",
    "THRESHOLD_STRONG   = df['approval_rate'].quantile(0.60)\n",
    "THRESHOLD_MODERATE = df['approval_rate'].quantile(0.30)\n",
    "print(f\"\\nApproval rate distribution:\")\n",
    "print(f\"  Mean:   {df['approval_rate'].mean():.1%}\")\n",
    "print(f\"  Median: {df['approval_rate'].median():.1%}\")\n",
    "print(f\"  ✅ Strong   (>= 60th pct): {THRESHOLD_STRONG:.1%}\")\n",
    "print(f\"  🟡 Moderate (>= 30th pct): {THRESHOLD_MODERATE:.1%}\")\n",
    "print(f\"  ❌ Low      (<  30th pct)\")\n",
    "\n",
    "df = df.sort_values(['form_id', 'fiscal_year', 'quarter']).reset_index(drop=True)\n",
    "df['pending_imp'] = df.groupby(['form_id', 'fiscal_year'])['pending_imp'].ffill()\n",
    "df['pending_imp'] = df['pending_imp'].fillna(\n",
    "    df.groupby(['form_id', 'quarter'])['pending_imp'].transform(lambda s: s.shift(1))\n",
    ")\n",
    "df['pending_imp'] = df['pending_imp'].fillna(\n",
    "    df.groupby('form_id')['pending_imp'].transform(\n",
    "        lambda s: s.shift(1).rolling(4, min_periods=1).median()\n",
    "    )\n",
    ")\n",
    "df['pending_imp'] = df['pending_imp'].fillna(\n",
    "    df.groupby('form_id')['pending_imp'].transform('median')\n",
    ")\n",
    "\n",
    "g = df.groupby('form_id')\n",
    "df['approval_rate_lag1']   = g['approval_rate'].shift(1)\n",
    "df['approval_rate_lag4']   = g['approval_rate'].shift(4)\n",
    "df['approval_rate_roll4']  = g['approval_rate'].transform(\n",
    "    lambda s: s.shift(1).rolling(4, min_periods=2).mean()\n",
    ")\n",
    "df['pending_imp_lag1']     = g['pending_imp'].shift(1)\n",
    "df['pending_imp_lag1_log'] = np.log1p(df['pending_imp_lag1'].clip(lower=0))\n",
    "df['pending_imp_trend']    = df['pending_imp_lag1'] - g['pending_imp'].shift(4)\n",
    "\n",
    "le = LabelEncoder()\n",
    "df['form_enc'] = le.fit_transform(df['form_id'].astype(str))\n",
    "\n",
    "FEATURES = [\n",
    "    'form_enc',\n",
    "    'approval_rate_lag1',\n",
    "    'approval_rate_lag4',\n",
    "    'approval_rate_roll4',\n",
    "    'pending_imp_lag1_log',\n",
    "    'pending_imp_trend',\n",
    "]\n",
    "\n",
    "df_model = df.dropna(subset=FEATURES + ['approval_rate']).copy()\n",
    "cutoff   = df_model['fiscal_year'].max() - 1\n",
    "train_df = df_model[df_model['fiscal_year'] <= cutoff]\n",
    "test_df  = df_model[df_model['fiscal_year'] >  cutoff]\n",
    "\n",
    "model = xgb.XGBRegressor(\n",
    "    n_estimators=400, learning_rate=0.05, max_depth=4,\n",
    "    subsample=0.8, colsample_bytree=0.8, min_child_weight=3,\n",
    "    random_state=42, verbosity=0,\n",
    "    early_stopping_rounds=40, eval_metric='rmse',\n",
    ")\n",
    "model.fit(\n",
    "    train_df[FEATURES], train_df['approval_rate'],\n",
    "    eval_set=[(test_df[FEATURES], test_df['approval_rate'])],\n",
    "    verbose=False,\n",
    ")\n",
    "\n",
    "preds = np.clip(model.predict(test_df[FEATURES]), 0, 1)\n",
    "print(f\"\\nMAE : {mean_absolute_error(test_df['approval_rate'], preds):.4f}\")\n",
    "print(f\"R²  : {r2_score(test_df['approval_rate'], preds):.4f}\")\n",
    "print(f\"Predicted spread (std): {preds.std():.1%}\")\n",
    "\n",
    "\n",
    "_history = (\n",
    "    df.sort_values(['form_id', 'fiscal_year', 'quarter'])\n",
    "    .groupby('form_id').last().reset_index()\n",
    ")\n",
    "\n",
    "def predict_approval(form_id: str):\n",
    "    \"\"\"\n",
    "    Predict approval outlook for a form based on its recent history.\n",
    "    No year or quarter needed — the model uses the form's latest known\n",
    "    approval trend and backlog to make the prediction.\n",
    "    \"\"\"\n",
    "    if form_id not in le.classes_:\n",
    "        print(f\"Form {form_id} not found. Available: {sorted(le.classes_)}\")\n",
    "        return\n",
    "    h = _history[_history['form_id'] == form_id]\n",
    "    if h.empty:\n",
    "        print(f\"No history for {form_id}\")\n",
    "        return\n",
    "    h = h.iloc[0]\n",
    "\n",
    "    row = pd.DataFrame([{\n",
    "        'form_enc':             le.transform([form_id])[0],\n",
    "        'approval_rate_lag1':   h.get('approval_rate_lag1'),\n",
    "        'approval_rate_lag4':   h.get('approval_rate_lag4'),\n",
    "        'approval_rate_roll4':  h.get('approval_rate_roll4'),\n",
    "        'pending_imp_lag1_log': np.log1p(max(0, float(h.get('pending_imp_lag1') or 0))),\n",
    "        'pending_imp_trend':    float(h.get('pending_imp_trend') or 0),\n",
    "    }])\n",
    "\n",
    "    rate = float(np.clip(model.predict(row), 0, 1)[0])\n",
    "\n",
    "    print(f\"\\nForm:     {form_id}\")\n",
    "    print(f\"Approval Probability: {rate:.1%}\")\n",
    "    if rate >= THRESHOLD_STRONG:\n",
    "        print(\"Outlook: ✅ Strong chance of approval\")\n",
    "    elif rate >= THRESHOLD_MODERATE:\n",
    "        print(\"Outlook: 🟡 Moderate chance of approval\")\n",
    "    else:\n",
    "        print(\"Outlook: ❌ Low chance of approval\")\n",
    "\n",
    "\n",
    "# NEW — replace with this\n",
    "results = []\n",
    "\n",
    "form_avg = df_model.groupby('form_id')[FEATURES + ['approval_rate']].mean().reset_index()\n",
    "\n",
    "for _, row_data in form_avg.iterrows():\n",
    "    form_id = row_data['form_id']\n",
    "    row = pd.DataFrame([{\n",
    "        'form_enc':             le.transform([form_id])[0],\n",
    "        'approval_rate_lag1':   row_data['approval_rate_lag1'],\n",
    "        'approval_rate_lag4':   row_data['approval_rate_lag4'],\n",
    "        'approval_rate_roll4':  row_data['approval_rate_roll4'],\n",
    "        'pending_imp_lag1_log': row_data['pending_imp_lag1_log'],\n",
    "        'pending_imp_trend':    row_data['pending_imp_trend'],\n",
    "    }])\n",
    "    rate    = float(np.clip(model.predict(row), 0, 1)[0])\n",
    "    outlook = '✅ Strong' if rate >= THRESHOLD_STRONG else ('🟡 Moderate' if rate >= THRESHOLD_MODERATE else '❌ Low')\n",
    "    results.append({\n",
    "        'form':          form_id,\n",
    "        'avg_actual':    f\"{row_data['approval_rate']:.1%}\",\n",
    "        'predicted':     f\"{rate:.1%}\",\n",
    "        'outlook':       outlook,\n",
    "    })\n",
    "\n",
    "results_df = pd.DataFrame(results).sort_values('predicted', ascending=False)\n",
    "print(results_df.to_string(index=False))\n",
    "results_df.to_csv(os.path.join(FOLDER, 'all_form_predictions.csv'), index=False)\n",
    "model.save_model(os.path.join(FOLDER, 'model_approval_regressor.json'))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "6d63ec54-21cb-40b3-b7a3-5b8b5a295ecd",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Pending backlog distribution:\n",
      "  Mean:   236,256\n",
      "  Median: 19,732\n",
      "  🔴 High backlog (>= 70th pct): 108,394\n",
      "  🟡 Medium       (>= 40th pct): 7,803\n",
      "  🟢 Low          (<  40th pct)\n",
      "\n",
      "MAE : 73,912\n",
      "R²  : 0.9681\n",
      "                                                       form avg_actual predicted backlog_ratio          outlook\n",
      "                                                      I-485  1,126,426   998,162        234.7%   🔴 High backlog\n",
      "                                                      I-140    121,092    98,209         81.5% 🟡 Medium backlog\n",
      "                    Annual Certification of Regional Center      1,779     9,792       5603.6% 🟡 Medium backlog\n",
      "                                                      I-800        711     9,792        536.7% 🟡 Medium backlog\n",
      "                                                      I-881        882     9,792       6537.5% 🟡 Medium backlog\n",
      "                                                      I-889        299     9,792        393.6% 🟡 Medium backlog\n",
      "                                                      I-899        518     9,792        118.1% 🟡 Medium backlog\n",
      "                                                      I-924      1,007     9,792       7104.4% 🟡 Medium backlog\n",
      "                                                     I-924A      3,418     9,792       6478.8% 🟡 Medium backlog\n",
      "                                                      I-929      2,571     9,792       1583.0% 🟡 Medium backlog\n",
      "                                                      I-956        224     9,792      10033.0% 🟡 Medium backlog\n",
      "                                                     I-956F        371     9,792       4365.0% 🟡 Medium backlog\n",
      "                                                     I-956G      1,301     9,792       1551.9% 🟡 Medium backlog\n",
      "                                                     I-956K      2,125     9,792       1283.7% 🟡 Medium backlog\n",
      "                                               Legalization        605     9,792      33348.2% 🟡 Medium backlog\n",
      "                                          Legalization/ SAW        258     9,792      97922.5% 🟡 Medium backlog\n",
      "                                             Legalization13        212     9,792      23883.5% 🟡 Medium backlog\n",
      "                                              Legalization6        262     9,792      33766.4% 🟡 Medium backlog\n",
      "                                                      N-300         48     9,792     414287.7% 🟡 Medium backlog\n",
      "                                                      I-817        598     9,792       4118.1% 🟡 Medium backlog\n",
      "                                                      I-867      2,994     9,792         43.1% 🟡 Medium backlog\n",
      "                                                      I-102      3,870     9,792        369.8% 🟡 Medium backlog\n",
      "                                                      I-193        737     9,792      34972.3% 🟡 Medium backlog\n",
      "                                                      I-600        727     9,792       1395.6% 🟡 Medium backlog\n",
      "                                                     I-601A    119,869    88,413        378.2% 🟡 Medium backlog\n",
      "                                                      I-360    147,547    88,413        161.1% 🟡 Medium backlog\n",
      "                                                       I-90    714,386   768,186        174.1%   🔴 High backlog\n",
      "                                                  Waivers23    789,733   708,555        574.3%   🔴 High backlog\n",
      "                                                      N-400    902,552   702,477        156.7%   🔴 High backlog\n",
      "                                                      N-600     73,172    65,091        165.4% 🟡 Medium backlog\n",
      "                                                     I-290B     64,950    64,043        129.7% 🟡 Medium backlog\n",
      "                                          EOIR Adjustment24     27,801    58,622        487.1% 🟡 Medium backlog\n",
      "                 Application for Certificate of Citizenship     42,456    56,957        417.5% 🟡 Medium backlog\n",
      "                       Immigrant Petition for Alien Workers     45,963    56,722        177.0% 🟡 Medium backlog\n",
      "                                                      I-131    542,831   509,652        139.6%   🔴 High backlog\n",
      "                                                     I-129F     45,071    48,099        183.5% 🟡 Medium backlog\n",
      "                                                      I-918    435,973   368,907       1173.3%   🔴 High backlog\n",
      "                                                      N-565     26,686    32,955        178.3% 🟡 Medium backlog\n",
      "                                                      I-751    324,788   310,398        404.0%   🔴 High backlog\n",
      "                                                      I-730     29,868    31,907        316.7% 🟡 Medium backlog\n",
      "                                                      I-526     18,555    28,360       2054.1% 🟡 Medium backlog\n",
      "                                                    Waivers    275,619   270,210        875.6%   🔴 High backlog\n",
      "                         Petition for U Nonimmigrant Status    254,339   262,896       2885.2%   🔴 High backlog\n",
      "                                                     I-526E     12,811    26,248        570.1% 🟡 Medium backlog\n",
      "                                            EOIR Adjustment     19,439    26,248        137.6% 🟡 Medium backlog\n",
      "                                                     I-956H     11,698    26,013       1060.5% 🟡 Medium backlog\n",
      "                                                      I-914     20,650    26,013        338.4% 🟡 Medium backlog\n",
      "                                                      I-824     20,278    26,013        197.9% 🟡 Medium backlog\n",
      "                                                      I-829     12,655    26,013       1659.6% 🟡 Medium backlog\n",
      "                                                      I-870     15,335    26,013         24.0% 🟡 Medium backlog\n",
      "                                                      I-821    460,392   205,018         68.8%   🔴 High backlog\n",
      "                                                      I-130  2,410,373 2,002,906        413.7%   🔴 High backlog\n",
      "                                                      I-129    155,507   169,739         56.2%   🔴 High backlog\n",
      "                                                     I-821D    167,569   168,648         89.9%   🔴 High backlog\n",
      "                                                      I-539    179,298   159,206        107.7%   🔴 High backlog\n",
      "                                                     DS-230    142,341   135,015         30.0%   🔴 High backlog\n",
      "                                                      N-336      5,404    13,993        470.0% 🟡 Medium backlog\n",
      "                      Application for T Nonimmigrant Status      3,607    13,993       2696.2% 🟡 Medium backlog\n",
      "                                                      N-470         99    11,075      23152.7% 🟡 Medium backlog\n",
      "                                                      N-648      2,591    11,075         32.0% 🟡 Medium backlog\n",
      "Petition for Qualifying Family Member of a U-1 Nonimmigrant      1,060    11,075       4820.3% 🟡 Medium backlog\n",
      "                                                      I-765  2,453,261 1,650,039         82.5%   🔴 High backlog\n",
      "                                                      I-589  1,092,289 1,006,566        588.5%   🔴 High backlog\n",
      "\n",
      "P(pending) model — MAE: 0.0867\n",
      "P(pending) model — R²:  0.7930\n",
      "\n",
      "==================================================\n",
      "                                                       form avg_actual p_left_pending\n",
      "                                                     I-956G      99.0%          98.7%\n",
      "                                             Legalization13     100.0%          98.0%\n",
      "                                                      I-193      96.3%          97.0%\n",
      "                                                      I-918      97.5%          96.9%\n",
      "                                                      I-589      99.0%          96.7%\n",
      "                         Petition for U Nonimmigrant Status      97.8%          96.5%\n",
      "                    Annual Certification of Regional Center     100.0%          96.0%\n",
      "                                                     DS-230     100.0%          95.4%\n",
      "                                                     I-956K      89.2%          95.4%\n",
      "                                                     I-526E      95.1%          95.3%\n",
      "                                                    Waivers      95.7%          95.0%\n",
      "                                                      I-889     100.0%          92.6%\n",
      "                                                     I-924A     100.0%          92.3%\n",
      "                                          Legalization/ SAW      91.1%          92.0%\n",
      "                                                     I-956H     100.0%          91.8%\n",
      "                                                  Waivers23      94.2%          91.8%\n",
      "                                                      I-924      92.6%          91.7%\n",
      "                                          EOIR Adjustment24     100.0%          91.4%\n",
      "                                                      I-867     100.0%          91.2%\n",
      "                                            EOIR Adjustment     100.0%          90.8%\n",
      "                                                      I-829      89.7%          90.4%\n",
      "                                                      I-130      89.1%          89.6%\n",
      "                                                      I-914      87.9%          88.3%\n",
      "                                                      I-881      88.6%          87.3%\n",
      "                                                      I-751      86.9%          86.8%\n",
      "                                                      I-929      86.0%          86.1%\n",
      "                      Application for T Nonimmigrant Status      81.1%          86.1%\n",
      "                                                      I-360      85.7%          85.6%\n",
      "                                               Legalization      94.0%          84.4%\n",
      "                                                      I-730      83.1%          83.6%\n",
      "                                                      I-526      85.2%          83.3%\n",
      "Petition for Qualifying Family Member of a U-1 Nonimmigrant      83.5%          82.9%\n",
      "                                              Legalization6      84.2%          82.4%\n",
      "                                                     I-601A      79.8%          82.1%\n",
      "                                                      I-485      82.3%          81.8%\n",
      "                                                     I-290B      69.6%          80.3%\n",
      "                                                      N-336      72.9%          77.1%\n",
      "                 Application for Certificate of Citizenship      79.1%          76.4%\n",
      "                                                      N-600      72.1%          75.9%\n",
      "                                                      I-817      73.5%          74.6%\n",
      "                                                      I-824      70.1%          74.3%\n",
      "                                                      N-400      73.4%          74.2%\n",
      "                                                      N-300      76.6%          74.1%\n",
      "                                                     I-956F      65.4%          73.9%\n",
      "                                                      I-956      68.7%          72.3%\n",
      "                                                       I-90      71.8%          71.1%\n",
      "                                                      N-565      68.0%          71.0%\n",
      "                                                     I-129F      70.5%          70.9%\n",
      "                                                      I-102      65.6%          67.9%\n",
      "                                                      I-821      68.7%          66.6%\n",
      "                                                      I-131      67.1%          65.9%\n",
      "                                                     I-821D      60.2%          63.4%\n",
      "                                                      I-539      59.1%          63.3%\n",
      "                                                      I-140      65.5%          62.7%\n",
      "                                                      I-600      57.7%          62.0%\n",
      "                                                      I-899      43.0%          61.2%\n",
      "                                                      N-470      61.4%          60.9%\n",
      "                                                      I-765      61.0%          60.1%\n",
      "                       Immigrant Petition for Alien Workers      59.1%          59.8%\n",
      "                                                      I-129      50.2%          52.1%\n",
      "                                                      N-648      50.4%          48.6%\n",
      "                                                      I-870      30.1%          46.7%\n",
      "                                                      I-800      40.7%          45.0%\n"
     ]
    }
   ],
   "source": [
    "FOLDER = '/Users/vals/Desktop/HACKATHON/'\n",
    "\n",
    "DESCRIPTION_TO_FORM = {\n",
    "    'Immediate and Preference Relatives': 'I-130',\n",
    "    'Immediate and Preference Relative':  'I-130',\n",
    "    'Family-Based Adjustments':           'I-485',\n",
    "    'Employment-Based Adjustments':       'I-485',\n",
    "    'Asylum Adjustments':                 'I-485',\n",
    "    'Refugee Adjustments':                'I-485',\n",
    "    'Cuban Adjustment Act':               'I-485',\n",
    "    'Other Adjustments of Status':        'I-485',\n",
    "    'Indo Chinese Adjustments':           'I-485',\n",
    "    'Military Naturalization':            'N-400',\n",
    "    'Orphan Petitions':                   'I-600',\n",
    "    'Convention Country Adoptions':       'I-800',\n",
    "    'Nonimmigrant Worker Petitions':      'I-129',\n",
    "    'Immigrant Petitions for Workers':    'I-140',\n",
    "}\n",
    "\n",
    "def clean_number(value):\n",
    "    if pd.isna(value):\n",
    "        return None\n",
    "    value = str(value).strip()\n",
    "    if value.upper() == 'D':\n",
    "        return None\n",
    "    if value in ('-', '–', '—', 'N/A', 'n/a', ''):\n",
    "        return 0\n",
    "    value = value.replace(',', '')\n",
    "    try:\n",
    "        return int(float(value))\n",
    "    except:\n",
    "        return None\n",
    "\n",
    "def is_numeric_cell(value) -> bool:\n",
    "    if pd.isna(value):\n",
    "        return True\n",
    "    s = str(value).strip().replace(',', '')\n",
    "    if s in ('D', '-', '–', '—', 'N/A', ''):\n",
    "        return True\n",
    "    try:\n",
    "        float(s)\n",
    "        return True\n",
    "    except:\n",
    "        return False\n",
    "\n",
    "def clean_form_number(form):\n",
    "    form = str(form).strip()\n",
    "    form = re.sub(r'\\s+\\d+$', '', form)\n",
    "    return form\n",
    "\n",
    "def get_year(filename):\n",
    "    match = re.search(r'fy(\\d{4}|\\d{2})', filename, re.IGNORECASE)\n",
    "    if not match:\n",
    "        return None\n",
    "    year = match.group(1)\n",
    "    return int('20' + year) if len(year) == 2 else int(year)\n",
    "\n",
    "def read_csv_safe(filepath):\n",
    "    for encoding in ['utf-8-sig', 'latin1', 'cp1252']:\n",
    "        try:\n",
    "            with open(filepath, 'rb') as f:\n",
    "                raw = f.read()\n",
    "            content = raw.decode(encoding, errors='replace')\n",
    "            content = content.replace('\\r\\n', '\\n').replace('\\r', '\\n')\n",
    "            lines   = content.split('\\n')\n",
    "            if ',' not in lines[0]:\n",
    "                content = '\\n'.join(lines[1:])\n",
    "            df = pd.read_csv(StringIO(content), header=None, on_bad_lines='skip')\n",
    "            if df.shape[0] > 1 and df.shape[1] > 1:\n",
    "                return df\n",
    "        except:\n",
    "            continue\n",
    "    return pd.DataFrame()\n",
    "\n",
    "def parse_old_file(filepath):\n",
    "    df       = read_csv_safe(filepath)\n",
    "    filename = os.path.basename(filepath)\n",
    "    year     = get_year(filename)\n",
    "\n",
    "    quarters_with_desc = {1:(3,4,5,6), 2:(7,8,9,10), 3:(11,12,13,14), 4:(15,16,17,18)}\n",
    "    quarters_no_desc   = {1:(2,3,4,5), 2:(6,7,8,9),  3:(10,11,12,13), 4:(14,15,16,17)}\n",
    "\n",
    "    start_row = 5\n",
    "    for i, row in df.iterrows():\n",
    "        if 'TOTAL' in str(row[0]).upper():\n",
    "            start_row = i + 1\n",
    "            break\n",
    "\n",
    "    rows = []\n",
    "    current_category = None\n",
    "\n",
    "    for i in range(start_row, len(df)):\n",
    "        row  = df.iloc[i]\n",
    "        col0 = str(row[0]).strip() if not pd.isna(row[0]) else ''\n",
    "        col1 = str(row[1]).strip() if not pd.isna(row[1]) else ''\n",
    "        col2 = str(row[2]).strip() if not pd.isna(row[2]) else ''\n",
    "\n",
    "        if not col0 and not col1:\n",
    "            continue\n",
    "        if col0 and not col1:\n",
    "            current_category = col0\n",
    "            continue\n",
    "        if not col1 or col1 == 'nan':\n",
    "            continue\n",
    "\n",
    "        form = col1\n",
    "        if is_numeric_cell(col2):\n",
    "            desc     = None\n",
    "            quarters = quarters_no_desc\n",
    "        else:\n",
    "            desc     = col2 if col2 not in ('nan', '') else None\n",
    "            quarters = quarters_with_desc\n",
    "\n",
    "        if form in DESCRIPTION_TO_FORM:\n",
    "            form = DESCRIPTION_TO_FORM[form]\n",
    "        if desc and desc in DESCRIPTION_TO_FORM:\n",
    "            form = DESCRIPTION_TO_FORM[desc]\n",
    "        form = clean_form_number(form)\n",
    "\n",
    "        for quarter_num, (r, a, d, p) in quarters.items():\n",
    "            received = clean_number(row[r]) if r < len(row) else None\n",
    "            approved = clean_number(row[a]) if a < len(row) else None\n",
    "            denied   = clean_number(row[d]) if d < len(row) else None\n",
    "            pending  = clean_number(row[p]) if p < len(row) else None\n",
    "            has_data = any(v is not None for v in [received, approved, denied, pending])\n",
    "            if has_data:\n",
    "                rows.append({\n",
    "                    'fiscal_year': year, 'quarter': quarter_num,\n",
    "                    'category': current_category, 'form_number': form,\n",
    "                    'description': desc, 'received': received,\n",
    "                    'approved': approved, 'denied': denied,\n",
    "                    'pending': pending, 'source_file': filename,\n",
    "                })\n",
    "    return pd.DataFrame(rows)\n",
    "\n",
    "\n",
    "def parse_new_file(filepath):\n",
    "    df       = read_csv_safe(filepath)\n",
    "    filename = os.path.basename(filepath)\n",
    "    year     = get_year(filename)\n",
    "\n",
    "    q_match = re.search(r'q(\\d)', filename, re.IGNORECASE)\n",
    "    quarter = int(q_match.group(1)) if q_match else None\n",
    "\n",
    "    header_row = None\n",
    "    for i, row in df.iterrows():\n",
    "        if any('Forms Received' in str(v) for v in row.values):\n",
    "            header_row = i\n",
    "            break\n",
    "    if header_row is None:\n",
    "        return pd.DataFrame()\n",
    "\n",
    "    headers = [str(v) for v in df.iloc[header_row].tolist()]\n",
    "    def find_all_columns(keyword):\n",
    "        return [i for i, h in enumerate(headers) if keyword.lower() in h.lower()]\n",
    "\n",
    "    col_received_list = find_all_columns('forms received')\n",
    "    col_approved_list = find_all_columns('approved')\n",
    "    col_denied_list   = find_all_columns('denied')\n",
    "    col_pending_list  = find_all_columns('pending')\n",
    "\n",
    "    rows = []\n",
    "    current_category = None\n",
    "\n",
    "    for i in range(header_row + 1, len(df)):\n",
    "        row  = df.iloc[i]\n",
    "        form = str(row[0]).strip() if not pd.isna(row[0]) else ''\n",
    "        desc = str(row[1]).strip() if not pd.isna(row[1]) else ''\n",
    "        if not form or form in ['nan', 'TOTAL', 'Total']:\n",
    "            continue\n",
    "        if not desc or desc == 'nan':\n",
    "            current_category = form\n",
    "            continue\n",
    "        if form in DESCRIPTION_TO_FORM:\n",
    "            form = DESCRIPTION_TO_FORM[form]\n",
    "        if desc in DESCRIPTION_TO_FORM:\n",
    "            form = DESCRIPTION_TO_FORM[desc]\n",
    "        form = clean_form_number(form)\n",
    "\n",
    "        received = sum(clean_number(row[c]) or 0 for c in col_received_list) or None\n",
    "        approved = sum(clean_number(row[c]) or 0 for c in col_approved_list) or None\n",
    "        denied   = sum(clean_number(row[c]) or 0 for c in col_denied_list)   or None\n",
    "        pending  = sum(clean_number(row[c]) or 0 for c in col_pending_list)  or None\n",
    "        has_data = any(v is not None for v in [received, approved, denied, pending])\n",
    "        if has_data:\n",
    "            rows.append({\n",
    "                'fiscal_year': year, 'quarter': quarter,\n",
    "                'category': current_category, 'form_number': form,\n",
    "                'description': desc, 'received': received,\n",
    "                'approved': approved, 'denied': denied,\n",
    "                'pending': pending, 'source_file': filename,\n",
    "            })\n",
    "    return pd.DataFrame(rows)\n",
    "\n",
    "\n",
    "all_files = [\n",
    "    f for f in glob.glob(os.path.join(FOLDER, '*.csv'))\n",
    "    if 'unified' not in os.path.basename(f).lower()\n",
    "]\n",
    "all_data = []\n",
    "for filepath in sorted(all_files):\n",
    "    filename = os.path.basename(filepath)\n",
    "    year     = get_year(filename)\n",
    "    try:\n",
    "        result = parse_new_file(filepath) if (year and year >= 2021) else parse_old_file(filepath)\n",
    "        if not result.empty:\n",
    "            all_data.append(result)\n",
    "    except Exception as error:\n",
    "        print(f\"  {filename} → ERROR: {error}\")\n",
    "\n",
    "final = pd.concat(all_data, ignore_index=True)\n",
    "final = final.sort_values(['fiscal_year', 'quarter', 'form_number']).reset_index(drop=True)\n",
    "\n",
    "for col in ['received', 'approved', 'denied', 'pending']:\n",
    "    final[col] = pd.to_numeric(final[col], errors='coerce')\n",
    "\n",
    "final = final.sort_values(['form_number', 'fiscal_year', 'quarter']).reset_index(drop=True)\n",
    "final['pending_last_year_same_q'] = final.groupby('form_number')['pending'].shift(4)\n",
    "final['pending_imp'] = final['pending'].copy()\n",
    "final['pending_imp'] = final['pending_imp'].fillna(final['pending_last_year_same_q'])\n",
    "final['pending_imp'] = final.groupby('form_number')['pending_imp'].ffill()\n",
    "final['pending_imp'] = final.groupby('form_number')['pending_imp'].bfill()\n",
    "final = final.drop(columns=['pending_last_year_same_q'])\n",
    "final['form_id'] = final['form_number'].str.extract(r'([A-Z]{1,4}-\\d{2,3}[A-Z]?)')\n",
    "final.to_csv(os.path.join(FOLDER, 'uscis_unified_2015_2025.csv'), index=False)\n",
    "\n",
    "\n",
    "df = final.copy()\n",
    "df['form_id'] = df['form_id'].fillna(df['form_number'])\n",
    "\n",
    "df = df.groupby(['fiscal_year', 'quarter', 'form_id'], as_index=False).agg(\n",
    "    received   =('received',    'sum'),\n",
    "    approved   =('approved',    'sum'),\n",
    "    denied     =('denied',      'sum'),\n",
    "    pending_imp=('pending_imp', 'sum'),\n",
    ")\n",
    "\n",
    "df = df.dropna(subset=['pending_imp', 'form_id'])\n",
    "df = df[df['pending_imp'] > 0].copy()\n",
    "\n",
    "THRESHOLD_HIGH = df['pending_imp'].quantile(0.70)   \n",
    "THRESHOLD_MED  = df['pending_imp'].quantile(0.40) \n",
    "\n",
    "print(f\"\\nPending backlog distribution:\")\n",
    "print(f\"  Mean:   {df['pending_imp'].mean():,.0f}\")\n",
    "print(f\"  Median: {df['pending_imp'].median():,.0f}\")\n",
    "print(f\"  🔴 High backlog (>= 70th pct): {THRESHOLD_HIGH:,.0f}\")\n",
    "print(f\"  🟡 Medium       (>= 40th pct): {THRESHOLD_MED:,.0f}\")\n",
    "print(f\"  🟢 Low          (<  40th pct)\")\n",
    "\n",
    "df = df.sort_values(['form_id', 'fiscal_year', 'quarter']).reset_index(drop=True)\n",
    "df['pending_imp'] = df.groupby(['form_id', 'fiscal_year'])['pending_imp'].ffill()\n",
    "df['pending_imp'] = df['pending_imp'].fillna(\n",
    "    df.groupby(['form_id', 'quarter'])['pending_imp'].transform(lambda s: s.shift(1))\n",
    ")\n",
    "df['pending_imp'] = df['pending_imp'].fillna(\n",
    "    df.groupby('form_id')['pending_imp'].transform(\n",
    "        lambda s: s.shift(1).rolling(4, min_periods=1).median()\n",
    "    )\n",
    ")\n",
    "df['pending_imp'] = df['pending_imp'].fillna(\n",
    "    df.groupby('form_id')['pending_imp'].transform('median')\n",
    ")\n",
    "\n",
    "g = df.groupby('form_id')\n",
    "df['pending_lag1']     = g['pending_imp'].shift(1)\n",
    "df['pending_lag4']     = g['pending_imp'].shift(4)\n",
    "df['pending_lag1_log'] = np.log1p(df['pending_lag1'].clip(lower=0))\n",
    "df['pending_lag4_log'] = np.log1p(df['pending_lag4'].clip(lower=0))\n",
    "df['pending_roll4']    = g['pending_imp'].transform(\n",
    "    lambda s: s.shift(1).rolling(4, min_periods=2).mean()\n",
    ")\n",
    "df['pending_trend']    = df['pending_lag1'] - df['pending_lag4']\n",
    "\n",
    "le = LabelEncoder()\n",
    "df['form_enc'] = le.fit_transform(df['form_id'].astype(str))\n",
    "\n",
    "FEATURES = [\n",
    "    'form_enc',\n",
    "    'pending_lag1_log',   \n",
    "    'pending_lag4_log',   \n",
    "    'pending_roll4',      \n",
    "    'pending_trend',   \n",
    "]\n",
    "\n",
    "\n",
    "df_model = df.dropna(subset=FEATURES + ['pending_imp']).copy()\n",
    "cutoff   = df_model['fiscal_year'].max() - 1\n",
    "train_df = df_model[df_model['fiscal_year'] <= cutoff]\n",
    "test_df  = df_model[df_model['fiscal_year'] >  cutoff]\n",
    "\n",
    "model = xgb.XGBRegressor(\n",
    "    n_estimators=400, learning_rate=0.05, max_depth=4,\n",
    "    subsample=0.8, colsample_bytree=0.8, min_child_weight=3,\n",
    "    random_state=42, verbosity=0,\n",
    "    early_stopping_rounds=40, eval_metric='rmse',\n",
    ")\n",
    "model.fit(\n",
    "    train_df[FEATURES], train_df['pending_imp'],\n",
    "    eval_set=[(test_df[FEATURES], test_df['pending_imp'])],\n",
    "    verbose=False,\n",
    ")\n",
    "\n",
    "preds = np.clip(model.predict(test_df[FEATURES]), 0, None)\n",
    "print(f\"\\nMAE : {mean_absolute_error(test_df['pending_imp'], preds):,.0f}\")\n",
    "print(f\"R²  : {r2_score(test_df['pending_imp'], preds):.4f}\")\n",
    "\n",
    "results = []\n",
    "\n",
    "form_avg = df_model.groupby('form_id')[FEATURES + ['pending_imp', 'received']].mean().reset_index()\n",
    "\n",
    "for _, row_data in form_avg.iterrows():\n",
    "    form_id = row_data['form_id']\n",
    "    row = pd.DataFrame([{\n",
    "        'form_enc':         le.transform([form_id])[0],\n",
    "        'pending_lag1_log': row_data['pending_lag1_log'],\n",
    "        'pending_lag4_log': row_data['pending_lag4_log'],\n",
    "        'pending_roll4':    row_data['pending_roll4'],\n",
    "        'pending_trend':    row_data['pending_trend'],\n",
    "    }])\n",
    "    pending_pred = float(max(0, model.predict(row)[0]))\n",
    "    received     = float(row_data['received']) if row_data['received'] > 0 else None\n",
    "    if received and received > 0:\n",
    "        backlog_pct = (pending_pred / received) * 100\n",
    "        backlog_str = f\"{backlog_pct:.1f}%\"\n",
    "    else:\n",
    "        backlog_str = \"N/A\"\n",
    "\n",
    "    outlook = (\n",
    "        '🔴 High backlog'   if pending_pred >= THRESHOLD_HIGH else\n",
    "        '🟡 Medium backlog' if pending_pred >= THRESHOLD_MED  else\n",
    "        '🟢 Low backlog'\n",
    "    )\n",
    "    results.append({\n",
    "        'form':           form_id,\n",
    "        'avg_actual':     f\"{row_data['pending_imp']:,.0f}\",\n",
    "        'predicted':      f\"{pending_pred:,.0f}\",\n",
    "        'backlog_ratio':  backlog_str,   # ← pending as % of received\n",
    "        'outlook':        outlook,\n",
    "    })\n",
    "\n",
    "results_df = pd.DataFrame(results).sort_values('predicted', ascending=False)\n",
    "print(results_df.to_string(index=False))\n",
    "results_df.to_csv(os.path.join(FOLDER, 'all_form_pending_predictions.csv'), index=False)\n",
    "df['p_pending'] = df['pending_imp'] / (\n",
    "    df['pending_imp'] + df['approved'].fillna(0) + df['denied'].fillna(0)\n",
    ")\n",
    "\n",
    "g = df.groupby('form_id')\n",
    "df['p_pending_lag1']  = g['p_pending'].shift(1)\n",
    "df['p_pending_lag4']  = g['p_pending'].shift(4)\n",
    "df['p_pending_roll4'] = g['p_pending'].transform(\n",
    "    lambda s: s.shift(1).rolling(4, min_periods=2).mean()\n",
    ")\n",
    "\n",
    "FEATURES_PEND_PROB = [\n",
    "    'form_enc',\n",
    "    'p_pending_lag1',\n",
    "    'p_pending_lag4', \n",
    "    'p_pending_roll4',\n",
    "    'pending_lag1_log',   \n",
    "    'pending_trend',      \n",
    "]\n",
    "\n",
    "df_pp    = df.dropna(subset=FEATURES_PEND_PROB + ['p_pending']).copy()\n",
    "cutoff   = df_pp['fiscal_year'].max() - 1\n",
    "train_pp = df_pp[df_pp['fiscal_year'] <= cutoff]\n",
    "test_pp  = df_pp[df_pp['fiscal_year'] >  cutoff]\n",
    "\n",
    "model_pp = xgb.XGBRegressor(\n",
    "    n_estimators=400, learning_rate=0.05, max_depth=4,\n",
    "    subsample=0.8, colsample_bytree=0.8, min_child_weight=3,\n",
    "    random_state=42, verbosity=0,\n",
    "    early_stopping_rounds=40, eval_metric='rmse',\n",
    ")\n",
    "model_pp.fit(\n",
    "    train_pp[FEATURES_PEND_PROB], train_pp['p_pending'],\n",
    "    eval_set=[(test_pp[FEATURES_PEND_PROB], test_pp['p_pending'])],\n",
    "    verbose=False,\n",
    ")\n",
    "\n",
    "preds_pp = np.clip(model_pp.predict(test_pp[FEATURES_PEND_PROB]), 0, 1)\n",
    "print(f\"\\nP(pending) model — MAE: {mean_absolute_error(test_pp['p_pending'], preds_pp):.4f}\")\n",
    "print(f\"P(pending) model — R²:  {r2_score(test_pp['p_pending'], preds_pp):.4f}\")\n",
    "\n",
    "_history_pp = (\n",
    "    df_pp.sort_values(['form_id', 'fiscal_year', 'quarter'])\n",
    "    .groupby('form_id').last().reset_index()\n",
    ")\n",
    "\n",
    "results_pp = []\n",
    "form_avg_pp = df_pp.groupby('form_id')[FEATURES_PEND_PROB + ['p_pending']].mean().reset_index()\n",
    "\n",
    "for _, row_data in form_avg_pp.iterrows():\n",
    "    form_id = row_data['form_id']\n",
    "    row = pd.DataFrame([{\n",
    "        'form_enc':            le.transform([form_id])[0],\n",
    "        'p_pending_lag1':      row_data['p_pending_lag1'],\n",
    "        'p_pending_lag4':      row_data['p_pending_lag4'],\n",
    "        'p_pending_roll4':     row_data['p_pending_roll4'],\n",
    "        'pending_lag1_log': row_data['pending_lag1_log'],\n",
    "        'pending_trend':    row_data['pending_trend'],\n",
    "    }])\n",
    "    prob = float(np.clip(model_pp.predict(row), 0, 1)[0])\n",
    "    results_pp.append({\n",
    "        'form':             form_id,\n",
    "        'avg_actual':       f\"{row_data['p_pending']:.1%}\",\n",
    "        'p_left_pending':   f\"{prob:.1%}\",\n",
    "    })\n",
    "\n",
    "results_pp_df = pd.DataFrame(results_pp).sort_values('p_left_pending', ascending=False)\n",
    "print(\"\\n\" + \"=\"*50)\n",
    "print(results_pp_df.to_string(index=False))\n",
    "results_pp_df.to_csv(os.path.join(FOLDER, 'prob_left_pending.csv'), index=False)\n",
    "\n",
    "model.save_model(os.path.join(FOLDER, 'model_pending_regressor.json'))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "9a09cd82-6ef2-4276-9872-ee95be6ad57c",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'number': 'I-130', 'label': 'I-130 — Petition for Alien Relative'}\n",
      "{'number': 'I-485', 'label': 'I-485 — Application to Register Permanent Residence or Adjust Status'}\n",
      "{'number': 'I-129', 'label': 'I-129 — Petition for Nonimmigrant Worker'}\n",
      "{'number': 'I-131', 'label': 'I-131 — Application for Travel Document'}\n",
      "{'number': 'I-140', 'label': 'I-140 — Immigrant Petition for Alien Workers'}\n",
      "{'number': 'I-360', 'label': 'I-360 — Petition for Amerasian, Widow(er), or Special Immigrant'}\n",
      "{'number': 'I-526', 'label': 'I-526 — Immigrant Petition by Alien Investor'}\n",
      "{'number': 'I-539', 'label': 'I-539 — Application to Extend/Change Nonimmigrant Status'}\n",
      "{'number': 'I-600', 'label': 'I-600 — Petition to Classify Orphan as an Immediate Relative'}\n",
      "{'number': 'I-601', 'label': 'I-601 — Application for Waiver of Grounds of Inadmissibility'}\n",
      "{'number': 'I-751', 'label': 'I-751 — Petition to Remove Conditions on Residence'}\n",
      "{'number': 'I-765', 'label': 'I-765 — Application for Employment Authorization'}\n",
      "{'number': 'I-800', 'label': 'I-800 — Petition to Classify Convention Adoptee as an Immediate Relative'}\n",
      "{'number': 'I-821', 'label': 'I-821 — Application for Temporary Protected Status'}\n",
      "{'number': 'I-821D', 'label': 'I-821D — Consideration of Deferred Action for Childhood Arrivals (DACA)'}\n",
      "{'number': 'I-864', 'label': 'I-864 — Affidavit of Support'}\n",
      "{'number': 'I-90', 'label': 'I-90 — Application to Replace Permanent Resident Card'}\n",
      "{'number': 'I-914', 'label': 'I-914 — Application for T Nonimmigrant Status'}\n",
      "{'number': 'I-918', 'label': 'I-918 — Petition for U Nonimmigrant Status'}\n",
      "{'number': 'N-400', 'label': 'N-400 — Application for Naturalization'}\n",
      "{'number': 'N-600', 'label': 'N-600 — Application for Certificate of Citizenship'}\n",
      "{'number': 'N-565', 'label': 'N-565 — Application for Replacement Naturalization/Citizenship Document'}\n"
     ]
    }
   ],
   "source": [
    "FORM_NAMES = {\n",
    "    'I-130':  'Petition for Alien Relative',\n",
    "    'I-485':  'Application to Register Permanent Residence or Adjust Status',\n",
    "    'I-129':  'Petition for Nonimmigrant Worker',\n",
    "    'I-131':  'Application for Travel Document',\n",
    "    'I-140':  'Immigrant Petition for Alien Workers',\n",
    "    'I-360':  'Petition for Amerasian, Widow(er), or Special Immigrant',\n",
    "    'I-526':  'Immigrant Petition by Alien Investor',\n",
    "    'I-539':  'Application to Extend/Change Nonimmigrant Status',\n",
    "    'I-600':  'Petition to Classify Orphan as an Immediate Relative',\n",
    "    'I-601':  'Application for Waiver of Grounds of Inadmissibility',\n",
    "    'I-751':  'Petition to Remove Conditions on Residence',\n",
    "    'I-765':  'Application for Employment Authorization',\n",
    "    'I-800':  'Petition to Classify Convention Adoptee as an Immediate Relative',\n",
    "    'I-821':  'Application for Temporary Protected Status',\n",
    "    'I-821D': 'Consideration of Deferred Action for Childhood Arrivals (DACA)',\n",
    "    'I-864':  'Affidavit of Support',\n",
    "    'I-90':   'Application to Replace Permanent Resident Card',\n",
    "    'I-914':  'Application for T Nonimmigrant Status',\n",
    "    'I-918':  'Petition for U Nonimmigrant Status',\n",
    "    'N-400':  'Application for Naturalization',\n",
    "    'N-600':  'Application for Certificate of Citizenship',\n",
    "    'N-565':  'Application for Replacement Naturalization/Citizenship Document',\n",
    "}\n",
    "FORM_OPTIONS = [\n",
    "    {'number': form_id, 'label': f'{form_id} — {title}'}\n",
    "    for form_id, title in FORM_NAMES.items()\n",
    "]\n",
    "\n",
    "def get_form_info(form_id: str) -> dict:\n",
    "    form_id = form_id.strip().upper()\n",
    "    name = FORM_NAMES.get(form_id)\n",
    "\n",
    "    result = {\n",
    "        'number': form_id,\n",
    "        'label': f'{form_id} — {name}' if name else 'Unknown Form'\n",
    "    }\n",
    "    return result\n",
    "for form in FORM_OPTIONS:\n",
    "    print(form)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
